### ISSUE TITLE
error ApolloError: Failed to fetch

### ISSUE THREAD

**Issue by gazjosef** [gazjosef/project-mgmt-app#1]
error ApolloError: Failed to fetch
    at new ApolloError (index.ts:89:1)
    at QueryManager.ts:1151:1
    at both (asyncMap.ts:30:1)
    at asyncMap.ts:19:1
    at new Promise (<anonymous>)
    at Object.then (asyncMap.ts:19:1)
    at Object.error (asyncMap.ts:31:1)
    at notifySubscription (module.js:137:1)
    at onNotify (module.js:176:1)
    at SubscriptionObserver.error (module.js:229:1)

**Comment by gazjosef** [comment]
// App.js

const client = new ApolloClient({
  uri: "http://localhost:5000/graphql",
  cache: new InMemoryCache(),
});

const client = new ApolloClient({
  uri: "http://localhost:5005/graphql",
  cache: new InMemoryCache(),
});

**Comment by gazjosef** [comment]
// App.js

// OLD CODE
const client = new ApolloClient({
uri: "http://localhost:5000/graphql",
cache: new InMemoryCache(),
});

// NEW CODE
const client = new ApolloClient({
uri: "http://localhost:5005/graphql",
cache: new InMemoryCache(),
});
